CREATE DATABASE commerce_shopping_cart;
CREATE DATABASE commerce_shopping_store;
CREATE DATABASE commerce_warehouse;
CREATE DATABASE commerce_order;
CREATE DATABASE commerce_delivery;
CREATE DATABASE commerce_payment;
CREATE DATABASE product_db;
CREATE DATABASE inventory_db;
CREATE DATABASE order_db;