name: Explore With Me API Tests

on:
  pull_request:
  workflow_call:

jobs:
  check-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Check repo not fork and public
        run: |
          REPO=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "/repos/${GITHUB_REPOSITORY}")
          FORK=$(jq '.fork' <<< "$REPO")
          PRIVATE=$(jq '.private' <<< "$REPO")
          echo "FORK='$FORK', PRIVATE='$PRIVATE', GITHUB_REPOSITORY_OWNER=${GITHUB_REPOSITORY_OWNER} "
          if [[ "$FORK" == "true" ]]
          then
            echo "Use the repository automatically created by Yandex Practicum (works in fork repositories are not accepted)"
            echo "Используйте только репозиторий созданный Yandex Practicum, работы в форк репозитории не принимаются"
            exit -1
          fi
          if [[ "$GITHUB_REPOSITORY_OWNER" == "yandex-praktikum" ]]
          then
            echo "Use the repository automatically created by Yandex Practicum (works in fork repositories are not accepted)"
            echo "Используйте только репозиторий созданный Yandex Practicum, работы в форк репозитории не принимаются"
            exit -2
          fi
          if [[ "$PRIVATE" == "true" && "$GITHUB_REPOSITORY_OWNER" != "praktikum-java" ]]
          then
            echo "Share your repository, make it public"
            echo "Откройте доступ к вашему репозиторию, сделайте его публичным"
            exit -3
          fi
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Check branch name
        run: |
          if [[ "$GITHUB_HEAD_REF" == "1-collector-json" ]]
          then
            echo "Collector json service - OK"
            if [[ "$GITHUB_BASE_REF" != "main" && "$GITHUB_REPOSITORY_OWNER" != "praktikum-java" ]]
            then
              echo "Set the pull request to merge branch 'main' (instead of '$GITHUB_BASE_REF')"
              echo "Задайте в Pull request ветку слияния 'main' (вместо '$GITHUB_BASE_REF')"
              exit -2
            fi
            echo "Github target '$GITHUB_BASE_REF' - OK"
            exit
          fi
          if [[ "$GITHUB_HEAD_REF" == "2-collector-grpc" ]]
          then
            echo "Collector grpc service - OK"
            PULL=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28"  /repos/${GITHUB_REPOSITORY}/pulls?head=${GITHUB_REPOSITORY_OWNER}:1-collector-json || true)
            OPEN=$(jq '. | length' <<< "$PULL")
            if [[ "$OPEN" != "0" && "$GITHUB_REPOSITORY_OWNER" != "praktikum-java" ]]
            then
              PULL_URL=$(jq '.[0].html_url' <<< "$PULL")
              echo "Merge the 1-collector-json branch pull request: ${PULL_URL}"
              echo "Объедините pull request ветки 1-collector-json: ${PULL_URL}"
              exit -3
            fi
            echo "Collector json service - Merged"
            if [[ "$GITHUB_BASE_REF" != "develop" && "$GITHUB_REPOSITORY_OWNER" != "praktikum-java" ]]
            then
              echo "Set the pull request to merge branch 'develop' (instead of '$GITHUB_BASE_REF')"
              echo "Задайте в Pull request ветку слияния 'develop' (вместо '$GITHUB_BASE_REF')"
              exit -2
            fi
            echo "Github target '$GITHUB_BASE_REF' - OK"
            exit
          fi
          if [[ "$GITHUB_HEAD_REF" == "3-aggregator" ]]
          then
            echo "Aggregator service - OK"
            PULL=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28"  /repos/${GITHUB_REPOSITORY}/pulls?head=${GITHUB_REPOSITORY_OWNER}:2-collector-grpc || true)
            OPEN=$(jq '. | length' <<< "$PULL")
            if [[ "$OPEN" != "0" && "$GITHUB_REPOSITORY_OWNER" != "praktikum-java" ]]
            then
              PULL_URL=$(jq '.[0].html_url' <<< "$PULL")
              echo "Merge the 2-collector-grpc branch pull request: ${PULL_URL}"
              echo "Объедините pull request ветки 2-collector-grpc: ${PULL_URL}"
              exit -4
            fi
            echo "Collector grpc service - Merged"
              if [[ "$GITHUB_BASE_REF" != "develop" && "$GITHUB_REPOSITORY_OWNER" != "praktikum-java" ]]
            then
              echo "Set the pull request to merge branch 'develop' (instead of '$GITHUB_BASE_REF')"
              echo "Задайте в Pull request ветку слияния 'develop' (вместо '$GITHUB_BASE_REF')"
              exit -2
            fi
            echo "Github target '$GITHUB_BASE_REF' - OK"
            exit
          fi
          if [[ "$GITHUB_HEAD_REF" == "4-analyzer" ]] 
          then
            echo "Analyzer service - OK"
            PULL=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28"  /repos/${GITHUB_REPOSITORY}/pulls?head=${GITHUB_REPOSITORY_OWNER}:3-aggregator || true)
            OPEN=$(jq '. | length' <<< "$PULL")
            if [[ "$OPEN" != "0" && "$GITHUB_REPOSITORY_OWNER" != "praktikum-java" ]]
            then
              PULL_URL=$(jq '.[0].html_url' <<< "$PULL")
              echo "Merge the 3-aggregator branch pull request: ${PULL_URL}"
              echo "Объедините pull request ветки 3-aggregator: ${PULL_URL}"
              exit -5
            fi
            echo "Aggregator service - Merged"
            if [[ "$GITHUB_BASE_REF" != "develop" && "$GITHUB_REPOSITORY_OWNER" != "praktikum-java" ]]
            then
              echo "Set the pull request to merge branch 'develop' (instead of '$GITHUB_BASE_REF')"
              echo "Задайте в Pull request ветку слияния 'develop' (вместо '$GITHUB_BASE_REF')"
              exit -2
            fi
            echo "Github target '$GITHUB_BASE_REF' - OK"
            exit
          fi
          if [[ "$GITHUB_HEAD_REF" == "develop" ]] 
          then
            echo "Analyzer service - OK"
            PULL=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28"  /repos/${GITHUB_REPOSITORY}/pulls?head=${GITHUB_REPOSITORY_OWNER}:4-analyzer || true)
            OPEN=$(jq '. | length' <<< "$PULL")
            if [[ "$OPEN" != "0" && "$GITHUB_REPOSITORY_OWNER" != "praktikum-java" ]]
            then
              PULL_URL=$(jq '.[0].html_url' <<< "$PULL")
              echo "Merge the 4-analyzer branch pull request: ${PULL_URL}"
              echo "Объедините pull request ветки 4-analyzer: ${PULL_URL}"
              exit -6
            fi
            echo "Analyzer service - Merged"
            if [[ "$GITHUB_BASE_REF" != "main" && "$GITHUB_REPOSITORY_OWNER" != "praktikum-java" ]]
            then
              echo "Set the pull request to merge branch 'main' (instead of '$GITHUB_BASE_REF')"
              echo "Задайте в Pull request ветку слияния 'main' (вместо '$GITHUB_BASE_REF')"
              exit -2
            fi
            echo "Github target '$GITHUB_BASE_REF' - OK"
            exit
          fi
          echo "Correct branch name '$GITHUB_HEAD_REF' according to the spec, allowed: 1-collector-json, 2-collector-grpc, 3-aggregator, 4-analyzer, develop"
          echo "Исправьте пожалуйста имя ветки '$GITHUB_HEAD_REF' согласно заданию, разрешены: 1-collector-json, 2-collector-grpc, 3-aggregator, 4-analyzer, develop"
          exit -1
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Check files
        run: |
          PULL=$(gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28"  /repos/${GITHUB_REPOSITORY}/pulls/${PULL_NUMBER}/files?per_page=100 || true)
          FILENAMES=$(jq '.[] | .filename' <<< "$PULL")
          if [[ "$FILENAMES"  =~ "api-tests.yml" ]]
          then
            echo "The pull request contains the api-tests.yml file and cannot be modified. Remove it from PR"
            echo "Pull request содержит файл api-tests.yml, его изменять нельзя. Удалите его из PR"
            exit -1
          fi
          if [[ "$FILENAMES"  =~ "checkstyle.xml" ]]
          then
            echo "The pull request contains the checkstyle.xml file and cannot be modified. Remove it from PR"
            echo "Pull request содержит файл checkstyle.xml, его изменять нельзя. Удалите его из PR"
            exit -2
          fi
          if [[ "$FILENAMES"  =~ ".class" ]] || [[ "$FILENAMES"  =~ ".jar" ]] || [[ "$FILENAMES"  =~ "mvn" ]] || [[ "$FILENAMES"  =~ ".DS_Store" ]] \
          || [[ "$FILENAMES"  =~ ".idea" ]] || [[ "$FILENAMES"  =~ ".iws" ]] || [[ "$FILENAMES"  =~ ".iml" ]] || [[ "$FILENAMES"  =~ ".ipr" ]] \
          || [[ "$FILENAMES"  =~ ".db" ]] || [[ "$FILENAMES"  =~ ".log" ]] || [[ "$FILENAMES"  =~ "out/" ]] || [[ "$FILENAMES"  =~ "target/" ]]
          then
            echo "The pull request contains the binary files. Remove them (*.class, *.jar, *.DS_Store ...) from PR"
            echo "Pull request содержит двоичные файлы. Удалите их (*.class, *.jar, *.DS_Store ...) из PR"
            exit -3
          fi
          echo "PR files - OK"
          exit
        env:
          PULL_NUMBER: ${{ github.event.number }}
          GH_TOKEN: ${{ github.token }}

  build-ewm:

    needs: check-repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Check and Build application
        run: |
          mvn verify --no-transfer-progress
