name: Smart Home Tech Tests (v2)

on:
  workflow_dispatch:
    inputs:
      verbose_mode:
        description: "Включить подробные логи во время тестов"
        required: false
        default: false
        type: boolean
      print_logs:
        description: "Включить вывод логов в консоль"
        required: false
        default: false
        type: boolean

jobs:
  build:
    uses: yandex-praktikum/plus-smart-home-tech/.github/workflows/wf_v2.yml@ci
    with:
      verbose_mode: ${{ inputs.verbose_mode }}
      print_logs: ${{ inputs.print_logs }}